disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - statement_position
  - todo
  - trailing_whitespace
  - type_name
  - vertical_whitespace

  - type_body_length

included:
  - Sources
  - Tests